# -*- coding: utf-8 -*-
"""GCPI-VAEGAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsNl8bJ1Orrwkwk1a8BukcqXhKx2cHBu
"""

# ---------------- Imports ----------------
import tensorflow as tf
import numpy as np
import keras
from keras import layers
import matplotlib.pyplot as plt
from scipy.io import loadmat
from google.colab import files

# ---------------- Upload file ----------------
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# ---------------- Load .mat ----------------
data = loadmat(file_name)

geom = data["geom_all"].astype("float32")
cl = data["CL_0_all"].astype("float32")
cd = data["CD_0_all"].astype("float32")

labels = np.concatenate([cl, cd], axis=1).astype("float32")

# ---------------- Dataset ----------------
batch_size = 32

dataset = tf.data.Dataset.from_tensor_slices((geom, labels))
dataset = dataset.shuffle(1024).batch(batch_size).prefetch(tf.data.AUTOTUNE)

# ---------------- Imports ----------------
import tensorflow as tf
import numpy as np
import keras
from keras import layers
import matplotlib.pyplot as plt

# ---------------- Hyperparameters ----------------
LatentDim = 4
Points   = 257
HalfP       = Points // 2 + 1

alpha      = 3.5
beta       = 0.08
LamADV = 0.3
LamSMOOTH = 0.3

LamPHYS = 1
Delay  = 2000
Warmup   = 2000

EpochPHYS = 200
Epoch1           = 30
Epoch2           = 50

freebits = 0.1

# ---------------- X Coordinate Grid ----------------
def make_canonical_x_full(n=257):
    HalfP   = n // 2 + 1
    beta   = np.linspace(0, np.pi, HalfP)
    x_HalfP = 0.5 * (1 - np.cos(beta))
    return np.concatenate([x_HalfP[::-1], x_HalfP[1:]]).astype(np.float32)

CANONICAL_X_FULL = make_canonical_x_full(Points)
CANONICAL_X_TF   = tf.constant(CANONICAL_X_FULL, dtype=tf.float32)

# ---------------- Preprocessing ----------------
def preprocess_from_canonical(geom_array, label_array):
    all_y, all_labels = [], []
    n_failed = 0

    for i in range(len(geom_array)):
        y = geom_array[i, :, 1].copy()

        te_avg = (y[0] + y[-1]) / 2.0
        y[0]   = te_avg
        y[-1]  = te_avg

        y_upper_le2te = y[:HalfP][::-1]
        y_lower_le2te = y[HalfP - 1:]

        if np.any(y_upper_le2te[1:-1] < y_lower_le2te[1:-1] - 0.002):
            n_failed += 1
            continue

        max_t = float(np.max(y_upper_le2te - y_lower_le2te))
        if max_t < 0.01 or max_t > 1.5:
            n_failed += 1
            continue

        all_y.append(y)
        all_labels.append(label_array[i])

    all_y      = np.array(all_y)[:, :, np.newaxis]
    all_labels = np.array(all_labels)
    return all_y, all_labels

# ---------------- Loss Functions ----------------
def reconstruction_loss(x, x_hat):
    return tf.reduce_mean(tf.reduce_sum(tf.square(x - x_hat), axis=[1, 2]))

def kl_loss(z_mean, z_log_var, freebits=freebits):
    kl_per_dim = -0.5 * (1 + z_log_var - tf.square(z_mean) - tf.exp(z_log_var))
    kl_per_dim = tf.maximum(kl_per_dim, freebits)
    return tf.reduce_mean(tf.reduce_sum(kl_per_dim, axis=1))

def smoothness_loss(x_hat):
    y     = x_hat[:, :, 0]
    d1    = y[:, 1:] - y[:, :-1]
    d2    = y[:, :-2] - 2.0 * y[:, 1:-1] + y[:, 2:]
    scale = tf.reduce_mean(tf.abs(d1), axis=1, keepdims=True) + 1e-8
    return tf.reduce_mean(tf.reduce_sum(tf.square(d2 / scale), axis=1))

def physics_weight_schedule(step, delay=Delay, ramp=Warmup, target=LamPHYS):
    progress = tf.maximum(0.0, (step - delay) / ramp)
    return target * tf.minimum(1.0, progress)

# ---------------- Model ----------------
def build_models(latent_dim=LatentDim, n_points=Points):

    class Sampling(layers.Layer):
        def call(self, inputs):
            z_mean, z_log_var = inputs
            eps = tf.random.normal(shape=tf.shape(z_mean))
            return z_mean + tf.exp(0.5 * z_log_var) * eps

    class ResizeUpsample(layers.Layer):
        def __init__(self, target_len, filters, **kwargs):
            super().__init__(**kwargs)
            self.target_len = target_len
            self.conv       = layers.Conv1D(filters, 3, padding="same", activation="relu")
        def call(self, x):
            up = tf.squeeze(tf.image.resize(tf.expand_dims(x, 1),
                            [1, self.target_len], method="bilinear"), 1)
            return self.conv(up)

    encoder_inputs = keras.Input(shape=(n_points, 1))
    x = layers.Conv1D(32,  3, 2, padding="same", activation="relu")(encoder_inputs)
    x = layers.Conv1D(64,  3, 2, padding="same", activation="relu")(x)
    x = layers.Conv1D(128, 3, 2, padding="same", activation="relu")(x)
    x = layers.Conv1D(256, 3, 2, padding="same", activation="relu")(x)
    x = layers.Flatten()(x)
    x = layers.Dense(256, activation="relu")(x)
    z_mean_out    = layers.Dense(latent_dim, name="z_mean")(x)
    z_log_var_out = layers.Dense(latent_dim, name="z_log_var")(x)
    z             = Sampling()([z_mean_out, z_log_var_out])
    encoder = keras.Model(encoder_inputs, [z_mean_out, z_log_var_out, z], name="encoder")

    latent_inputs = keras.Input(shape=(latent_dim,))
    x = layers.Dense(17 * 256, activation="relu")(latent_inputs)
    x = layers.Reshape((17, 256))(x)
    x = ResizeUpsample(33,  128)(x)
    x = ResizeUpsample(65,  64)(x)
    x = ResizeUpsample(129, 32)(x)
    x = ResizeUpsample(257, 16)(x)
    x = layers.Conv1D(1, 3, padding="same")(x)
    decoder = keras.Model(latent_inputs, x, name="decoder")

    phys_in = keras.Input(shape=(n_points, 1))
    p = layers.Conv1D(32,  3, 2, padding="same", activation="relu")(phys_in)
    p = layers.Conv1D(64,  3, 2, padding="same", activation="relu")(p)
    p = layers.Conv1D(128, 3, 2, padding="same", activation="relu")(p)
    p = layers.GlobalAveragePooling1D()(p)
    p = layers.Dense(128, activation="relu")(p)
    p = layers.Dense(64,  activation="relu")(p)
    physics_model = keras.Model(phys_in, layers.Dense(2)(p), name="physics_model")

    disc_in = keras.Input(shape=(n_points, 1))
    d = layers.Conv1D(32,  3, 2, padding="same")(disc_in)
    d = layers.LeakyReLU(0.2)(d)
    d = layers.Conv1D(64,  3, 2, padding="same")(d)
    d = layers.LeakyReLU(0.2)(d)
    d = layers.Conv1D(128, 3, 2, padding="same")(d)
    d = layers.LeakyReLU(0.2)(d)
    d = layers.Conv1D(256, 3, 2, padding="same")(d)
    d = layers.LeakyReLU(0.2)(d)
    d = layers.GlobalAveragePooling1D()(d)
    d = layers.Dense(128)(d)
    d = layers.LeakyReLU(0.2)(d)
    discriminator = keras.Model(disc_in, layers.Dense(1)(d), name="discriminator")

    return encoder, decoder, physics_model, discriminator

# ---------------- Phase 1 ----------------
class VAEPhase1(keras.Model):
    def __init__(self, encoder, decoder):
        super().__init__()
        self.encoder = encoder
        self.decoder = decoder

    def compile(self, optimizer):
        super().compile()
        self.optimizer = optimizer

    def train_step(self, data):
        x, _ = data
        with tf.GradientTape() as tape:
            zm, zlv, z = self.encoder(x, training=True)
            x_hat      = self.decoder(z, training=True)
            recon  = reconstruction_loss(x, x_hat)
            kl     = kl_loss(zm, zlv)
            smooth = smoothness_loss(x_hat)
            loss   = (alpha         * recon  +
                      beta          * kl     +
                      LamSMOOTH * smooth)
        grads = tape.gradient(loss, self.encoder.trainable_weights +
                                    self.decoder.trainable_weights)
        self.optimizer.apply_gradients(zip(grads,
                      self.encoder.trainable_weights +
                      self.decoder.trainable_weights))
        return {"loss": loss, "recon": recon, "kl": kl, "smooth": smooth}

# ---------------- Phase 2 ----------------
class VAEGANPhase2(keras.Model):
    def __init__(self, encoder, decoder, discriminator, physics_model):
        super().__init__()
        self.encoder       = encoder
        self.decoder       = decoder
        self.discriminator = discriminator
        self.physics_model = physics_model
        self.step = tf.Variable(0, trainable=False, dtype=tf.float32)

    def compile(self, vae_opt, d_opt, loss_fn):
        super().compile()
        self.vae_opt = vae_opt
        self.d_opt   = d_opt
        self.loss_fn = loss_fn

    def train_step(self, data):
        x, labels = data
        self.step.assign_add(1)
        phys_weight = physics_weight_schedule(self.step)

        zm, zlv, z = self.encoder(x, training=False)
        x_hat      = self.decoder(z, training=False)
        with tf.GradientTape() as tape:
            real_logits = self.discriminator(x,     training=True)
            fake_logits = self.discriminator(x_hat, training=True)
            z_rand      = tf.random.normal((tf.shape(x)[0], LatentDim))
            fake_rand   = self.discriminator(
                self.decoder(z_rand, training=False), training=True)
            d_loss = (
                self.loss_fn(tf.ones_like(real_logits),  real_logits) +
                self.loss_fn(tf.zeros_like(fake_logits), fake_logits) +
                self.loss_fn(tf.zeros_like(fake_rand),   fake_rand)
            )
        d_grads = tape.gradient(d_loss, self.discriminator.trainable_weights)
        self.d_opt.apply_gradients(zip(d_grads, self.discriminator.trainable_weights))

        with tf.GradientTape() as tape:
            zm, zlv, z = self.encoder(x, training=True)
            x_hat      = self.decoder(z, training=True)
            recon  = reconstruction_loss(x, x_hat)
            kl     = kl_loss(zm, zlv)
            smooth = smoothness_loss(x_hat)
            pred_fake        = self.physics_model(x_hat, training=False)
            pred_real        = self.physics_model(x,     training=False)
            phys_loss        = tf.reduce_mean(tf.square(pred_fake - labels))
            phys_consistency = tf.reduce_mean(tf.square(pred_real - pred_fake))
            adv_logits       = self.discriminator(x_hat, training=False)
            adv_loss         = self.loss_fn(tf.ones_like(adv_logits), adv_logits)
            vae_loss = (
                alpha         * recon  +
                beta          * kl     +
                LamSMOOTH * smooth +
                LamADV    * adv_loss +
                phys_weight   * (phys_loss + phys_consistency)
            )
        vae_vars = (self.encoder.trainable_weights +
                    self.decoder.trainable_weights)
        grads = tape.gradient(vae_loss, vae_vars)
        self.vae_opt.apply_gradients(zip(grads, vae_vars))

        return {
            "vae_loss": vae_loss, "recon": recon, "kl": kl,
            "smooth": smooth,
            "physics": phys_loss, "phys_con": phys_consistency,
            "phys_w": phys_weight, "adv": adv_loss, "d_loss": d_loss,
        }

# ---------------- Run ----------------
y_data, label_data = preprocess_from_canonical(geom, labels)

y_dataset = (tf.data.Dataset
               .from_tensor_slices((y_data, label_data))
               .shuffle(2000).batch(32).prefetch(tf.data.AUTOTUNE))

encoder, decoder, physics_model, discriminator = build_models()

vae_p1 = VAEPhase1(encoder, decoder)
vae_p1.compile(optimizer=keras.optimizers.Adam(1e-3))
vae_p1.fit(y_dataset, epochs=Epoch1, verbose=1)

physics_model.compile(optimizer=keras.optimizers.Adam(1e-3), loss="mse")
physics_model.fit(y_dataset, epochs=EpochPHYS, verbose=1)
physics_model.trainable = False

model = VAEGANPhase2(encoder, decoder, discriminator, physics_model)
model.compile(
    vae_opt=keras.optimizers.Adam(5e-4),
    d_opt   =keras.optimizers.Adam(2e-4),
    loss_fn =keras.losses.BinaryCrossentropy(from_logits=True)
)
model.fit(y_dataset, epochs=Epoch2, verbose=1)